"use client";
import { createElement, useEffect, useMemo, useRef, useState } from "react";
import { Atom, Bookmark, Bot, CalendarDays, ChevronDown, ChevronRight, ChevronUp, Cpu, Download, Globe2, House, Newspaper, Pause, Play, Search, Share2, Square, ThumbsDown, ThumbsUp, UserRoundPlus, Volume2, X } from "lucide-react";
import "./stellar.css";

type Story={id:string;section:string;kicker:string;title:string;summary:string;full?:string;source:string;url:string;time:string};
const todayStories:Story[]=[
{id:"ai-1",section:"AI",kicker:"今日首选 · 8月14日",title:"Claude 将为生成文本加入不可见水印",summary:"Anthropic 公布文本水印方案：不添加隐藏字符、不增加 token，并计划推出检测 API。",full:"Anthropic 8 月 14 日宣布，未来 Claude 模型生成的文本将包含不可见水印，以满足欧盟《人工智能法案》关于生成内容标记的要求。它采用 SynthID-Text 路线，不是在文字里塞入隐藏字符，而是在模型面对多个同样合理的下一个词时，用密钥控制随机选择，从而留下可统计检测的模式。\n\nAnthropic 表示，水印不会增加 token、不会提高价格，也不会携带用户、组织或对话身份。短文本、事实性文字、代码和轻度校对的可检测性会更弱，完整改写也可能移除水印。公司计划提供检测 API。\n\n为什么重要：生成内容的“来源证明”开始从倡议进入模型默认能力。对内容平台和企业来说，水印只能说明 AI 可能参与过，不能独立证明作者身份或内容真伪，因此仍需配合 C2PA、审计记录和人工核验。",source:"Anthropic",url:"https://www.anthropic.com/news/claude-text-watermark",time:"7 分钟"},
{id:"ai-2",section:"AI",kicker:"Agent · 8月12日",title:"企业 AI 正从“回答问题”转向“直接执行工作”",summary:"OpenAI 的两项研究显示，领先企业更频繁地把 AI 接入工具、上下文和可重复工作流。",full:"OpenAI 8 月 12 日发布两项企业使用研究。其数据表明，AI 在企业中的使用正在从辅助思考转向完成多步骤工作。按每位活跃用户的输出量衡量，使用最深入的前 10% 企业，是典型企业的 8.3 倍；这一差距在 1 月时为 2.6 倍。\n\n截至 6 月，Codex 在企业客户的 Codex 与 ChatGPT 合计输出 token 中占 64%。自 2 月以来，企业 Codex 周活跃用户在法律、销售、招聘和市场岗位上的增长，明显快于工程岗位。\n\n产品启发：模型能力只是起点。真正拉开差距的是能否接入企业上下文和工具，并建立权限、人工复核、治理与可复制的团队工作流。",source:"OpenAI",url:"https://openai.com/index/how-enterprises-put-ai-to-work/",time:"8 分钟"},
{id:"ai-3",section:"AI",kicker:"开放模型 · 8月10日",title:"Meta 发布可在个人电脑运行的 Muse Glimmer",summary:"Meta 再次押注开放模型，并提出让个人拥有通用 AI 助手的长期愿景。",full:"据美联社报道，Meta 8 月 10 日发布新的开放模型 Muse Glimmer，可在个人电脑上运行，同时向开发者提供更强的 Muse Spark 1.2。Mark Zuckerberg 在一篇长文中提出，未来每个人都可能拥有帮助学习、创业和生活决策的个人 AI。\n\n这次发布的重点不只是模型分数，而是“足够强、成本更低、可本地运行”的组合。它让隐私敏感、离线和低成本应用获得更多选择，也重新加剧开放权重与封闭前沿模型之间的竞争。\n\n需要继续观察：模型真实能力、许可证边界、端侧资源占用和安全评测，仍要以技术报告和独立测试为准。",source:"Associated Press",url:"https://apnews.com/article/meta-ai-mark-zuckerberg-artificial-intelligence-df8a4e7d7825470d09e8090367457c2c",time:"6 分钟"},
{id:"ai-4",section:"AI",kicker:"产业观察 · 8月13日",title:"模型竞争进入“能力 × 价格”的新阶段",summary:"新模型以更低成本逼近前沿水平，市场选择开始从单一榜单转向综合性价比。",full:"Axios 8 月 13 日报道，SpaceX 与 Meta 本周推出的新模型，在性能与价格的组合上对前沿实验室形成新的压力。报道援引 Artificial Analysis 指标称，Grok 4.6 的综合表现接近当时的头部系统；Meta 则以可在笔记本运行的开放模型从成本端切入。\n\n这意味着模型采购不能只看最高分。对绝大多数产品，响应速度、推理成本、上下文长度、可部署位置、稳定性和许可证，都会与纯能力一起决定最终价值。\n\n我们的判断：未来更常见的架构是模型路由——高频简单任务交给便宜模型，困难或高风险任务再升级到前沿模型。",source:"Axios",url:"https://www.axios.com/2026/08/13/grok-elon-musk-ai-zuckerberg-and-meta",time:"6 分钟"},
{id:"ai-5",section:"AI",kicker:"研究 · 7月23日",title:"Google 用 1500 万次交互观察真实世界如何使用 AI",summary:"ATLAS 研究覆盖 150 多个国家：AI 目前更多是协作工具，完全自动化仍然少见。",full:"Google 的 ATLAS v1.0 基于 Gemini App、AI Mode 和 Gemini API 中 1500 万次聚合、去标识化交互，覆盖 150 多个国家、140 种语言、800 个职业和 4000 类任务。\n\n研究显示，AI 已覆盖美国约 68% 的职业，但在典型岗位中只用于约 21% 的任务；工作场景主要是构思、检索、学习和协作，完全自动完成的交互不到 10%。AI 也在帮助汽车技师和工业机械师等职业进行诊断和现场学习。\n\n为什么重要：现实中的 AI 采用并不是一次性替代整个岗位，而是先渗透到具体任务。产品应围绕工作步骤设计，而不是只围绕职业标签或笼统的“自动化”叙事。",source:"Google",url:"https://blog.google/innovation-and-ai/technology/research/understanding-the-ai-economy/",time:"8 分钟"},
{id:"emb-1",section:"具身智能",kicker:"World Model · Paper Radar",title:"AlayaWorld v1.1 让生成世界拥有更长期的空间记忆",summary:"约 15B 参数的视频世界模型用流式 3D 点缓存减少长时间交互中的空间漂移。",full:"AlayaWorld v1.1 试图解决世界模型最关键的工程问题之一：不是生成几秒钟好看的视频，而是让环境在持续交互后仍保持空间一致。团队引入 Streaming 3D Point Cache Renderer，并让视觉条件与生成视频共享更一致的潜表示和时间结构。\n\n它连接了游戏生成、机器人训练、自动驾驶模拟与 Physical AI。当前结果来自新预印本，仍需等待独立复现与真实系统评测。",source:"arXiv",url:"https://arxiv.org/abs/2608.13492",time:"8 分钟"},
{id:"tech-1",section:"科技",kicker:"全球科技 TOP 5 · 算力",title:"NVIDIA 推动超 5000 亿美元 AI 算力融资体系",summary:"GPU、数据中心合同与未来算力收入正在被组织成可以融资的基础设施资产。",full:"Reuters 8 月 14 日报道，NVIDIA 正与 Apollo、BlackRock、Blackstone、Brookfield、Goldman Sachs、KKR 等机构合作推动 AI Compute Financing，潜在规模超过 5000 亿美元。\n\nNVIDIA 的角色正在从单纯卖芯片扩展为帮助客户和数据中心获得融资。如果这种模式跑通，算力可能像飞机、电站和房地产一样，依靠长期租赁现金流进行再融资；风险则是模型效率快速提升或需求不足导致资产利用率下降。",source:"Reuters",url:"https://www.reuters.com/legal/transactional/private-credit-roundup-nvidias-half-trillion-chips-financing-plus-others-2026-08-14/",time:"7 分钟"},
{id:"news-1",section:"新闻",kicker:"世界 TOP 5 · AI治理",title:"欧盟生成式 AI 透明度要求开始进入模型默认能力",summary:"主要模型提供商开始落实生成内容标记，AI 治理从原则逐步进入产品实现。",full:"Anthropic 表示将为未来 Claude 模型生成的文本加入水印，以遵循欧盟生成内容透明度要求。约 190 个签署方参与相关实践准则。\n\n这件事的影响超出单一产品：生成内容标记、检测接口、文件内容凭证和平台披露机制将逐步组成新的数字内容基础设施。但水印只能表示 AI 可能参与，不能代替事实核查。",source:"Anthropic",url:"https://www.anthropic.com/news/claude-text-watermark",time:"6 分钟"}];
const archives:Record<string,Story[]>={
"2026-08-14":[{id:"ai-0814",section:"AI",kicker:"模型进展",title:"小模型开始承担更多端侧智能任务",summary:"模型压缩与端侧芯片协同，让更多智能能力无需持续连接云端。",full:"端侧模型的关键价值不仅是速度，更是隐私、离线可用性和成本可控。产品将逐渐从所有请求发往云端，变为本地与云端按任务难度动态分流。",source:"MIT Technology Review",url:"https://www.technologyreview.com/",time:"5 分钟"},{id:"emb-0814",section:"具身智能",kicker:"机器人",title:"通用机器人数据集进入规模化阶段",summary:"跨平台操作数据正在帮助机器人学习更稳定的通用动作表示。",full:"新的训练方法尝试把视觉、语言和动作映射到共享表示，再针对具体机器人完成适配，从而降低每种机器人重复采集数据的成本。",source:"Google DeepMind",url:"https://deepmind.google/discover/blog/",time:"6 分钟"},{id:"tech-0814",section:"科技",kicker:"硬件",title:"空间计算设备继续向轻量化演进",summary:"显示、传感器和电池技术正在共同缩小设备体积。",source:"Apple Newsroom",url:"https://www.apple.com/newsroom/",time:"4 分钟"},{id:"news-0814",section:"新闻",kicker:"中国 TOP 5",title:"国内产业政策与科技投资持续受到关注",summary:"本地完整摘要整合公开信息，保留来源用于核验。",source:"新华社",url:"https://www.news.cn/",time:"6 分钟"}],
"2026-08-13":[{id:"ai-0813",section:"AI",kicker:"Agent",title:"智能体评测从答案质量转向任务成功率",summary:"长任务中的恢复能力、工具调用和结果验证成为新的评价重点。",source:"OpenAI",url:"https://openai.com/research/",time:"6 分钟"},{id:"emb-0813",section:"具身智能",kicker:"World Model",title:"世界模型正在学习更长时间尺度的预测",summary:"机器人需要理解动作在更长时间后产生的连锁影响。",source:"arXiv",url:"https://arxiv.org/",time:"8 分钟"},{id:"tech-0813",section:"科技",kicker:"全球科技",title:"低功耗 AI 芯片成为基础设施重点",summary:"推理需求增长正在重塑数据中心与终端设备的芯片组合。",source:"IEEE Spectrum",url:"https://spectrum.ieee.org/",time:"5 分钟"},{id:"news-0813",section:"新闻",kicker:"世界 TOP 5",title:"全球市场聚焦技术投资与供应链变化",summary:"站内摘要按影响范围、持续时间和可信度整理。",source:"Reuters",url:"https://www.reuters.com/world/",time:"7 分钟"}],
"2026-07-10":[{id:"ros-0710",section:"具身智能",kicker:"系统学习 · ROS",title:"ROS 2：具身智能系统的工程骨架",summary:"从节点、主题、服务到动作，理解 ROS 2 如何组织完整机器人系统。",full:"ROS 2 不是机器人本身的智能模型，而是连接传感器、算法和执行器的软件基础设施。节点负责独立功能，主题用于连续数据流，服务处理短请求，动作适合可以反馈进度的长任务。\n\n学习具身智能时，可以先用 ROS 2 搭建感知—规划—控制闭环，再逐步接入 VLA 模型和世界模型。",source:"ROS Documentation",url:"https://docs.ros.org/",time:"12 分钟"}]};
const nav=["今日","AI","具身智能","科技","前沿科学","新闻","收藏"];
const navIcons:Record<string,typeof House>={"今日":House,"AI":Bot,"具身智能":Cpu,"科技":Globe2,"前沿科学":Atom,"新闻":Newspaper,"收藏":Bookmark};
const dates=[{key:"today",label:"今天",sub:"8月15日"},{key:"2026-08-14",label:"昨天",sub:"8月14日"},{key:"2026-08-13",label:"星期四",sub:"8月13日"},{key:"2026-07-10",label:"7月10日",sub:"星期五"}];
archives["2026-08-13"].push({id:"ros-0813",section:"具身智能",kicker:"工具链 · ROS",title:"ROS 2 仿真到真机的部署路径",summary:"同一套节点图如何从仿真环境迁移到真实机器人。",full:"ROS 2 通过统一接口隔离算法和硬件差异。开发者可以先在仿真中验证导航、抓取和状态机，再替换驱动层接入真机。",source:"ROS Documentation",url:"https://docs.ros.org/",time:"9 分钟"});
todayStories.push({id:"science-1",section:"前沿科学",kicker:"数学 · AI for Science",title:"AI 解出 Erdős 数学问题，也引发证明核验与署名讨论",summary:"结果本身得到认可，但过程暴露出 AI 科研时代关于复核、开放性和贡献归属的新问题。",full:"AI 系统参与解决一个 Erdős 数学问题后，数学界关注的不只是答案正确与否，也包括证明是否可以独立检查、训练材料如何引用、人的贡献如何确认。\n\n这类案例说明 AI for Science 的评价需要同时覆盖结果、过程可追溯性、复现和学术信用，而不能只看最终解答。",source:"Science News",url:"https://www.sciencenews.org/article/ai-erdos-math-problem-guardrails",time:"7 分钟"});
todayStories.push(
{id:"emb-2",section:"具身智能",kicker:"World Foundation Model",title:"Xiaomi-Robotics-U0 把世界模型变成机器人数据引擎",summary:"38B 多模态模型统一生成多视角场景、机器人迁移和具身视频。",full:"Xiaomi-Robotics-U0 把具身生成视为图像与视频基础模型的扩展，同时训练文本生成图像、编辑、具身场景、多本体迁移和视频生成。论文报告称，它在困难真实操作任务中把 π0.5 的分布外成功率从 36.9% 提升到 63.2%。\n\n这条路线的价值是用世界模型生成结构一致的训练数据，降低真实机器人采集成本。结果仍应结合公开代码、检查点和第三方复现判断。",source:"arXiv",url:"https://arxiv.org/abs/2607.11643",time:"8 分钟"},
{id:"emb-3",section:"具身智能",kicker:"Physical AI · 产业",title:"Unitree 的资本热度反映人形机器人进入规模化验证期",summary:"市场开始用收入、海外销售和制造能力，而不只是 Demo 评价机器人公司。",full:"8 月中旬市场对 Unitree 上市进程的高关注，显示 Physical AI 正从实验室展示进入资本、供应链和规模制造阶段。值得看的不是短期申购热度，而是机器人企业是否能持续交付、采集高质量数据并形成软硬件闭环。\n\n后续应持续跟踪 VLA、World Model、Sim2Real、可靠性和单位成本。",source:"Reuters",url:"https://www.reuters.com/world/asia-pacific/what-is-unitree-why-are-chinas-humanoid-robot-makers-racing-list-2026-08-10/",time:"7 分钟"},
{id:"emb-4",section:"具身智能",kicker:"系统安全",title:"具身智能落地的核心不只能力，还有全生命周期安全",summary:"真实机器人必须同时处理感知误差、控制风险、人机协作和持续治理。",full:"SAE World Congress 2026 的具身智能白皮书把安全、信任、机器人和真实部署放在同一系统框架下。其核心观点是，具身 AI 不能只按模型指标管理，而应覆盖设计、验证、部署、监控和事故响应全生命周期。\n\n对企业产品，权限边界、紧急停止、仿真测试、可解释日志和人类监督应从第一天进入架构。",source:"arXiv / SAE",url:"https://arxiv.org/abs/2605.10653",time:"7 分钟"},
{id:"emb-5",section:"具身智能",kicker:"学习路线 · ROS 2",title:"ROS 2 仍是连接 VLA、规划、控制与硬件的重要工程层",summary:"模型负责理解和决策，ROS 2 负责把感知、动作与真实设备组织成系统。",full:"VLA 与世界模型并不会取代机器人中间件。ROS 2 的节点、主题、服务和动作机制，仍承担传感器数据流、硬件驱动、长任务反馈和模块隔离。\n\n建议学习顺序：ROS 2 基础 → 仿真 → 导航与机械臂 → 感知规划控制闭环 → 接入 VLA → 真机安全与部署。",source:"ROS Documentation",url:"https://docs.ros.org/",time:"9 分钟"},
{id:"tech-2",section:"科技",kicker:"全球科技 TOP 5 · 芯片",title:"NVIDIA 披露对 SpaceX 的约 210 亿美元持仓",summary:"AI 芯片、云计算与航天基础设施之间的资本联系进一步加深。",full:"公开监管披露显示，NVIDIA 在二季度末持有规模可观的 SpaceX 投资。它反映的不只是财务投资，还体现 AI 训练、卫星网络、数据中心和算力需求之间越来越紧密的产业关系。\n\n需要区分战略协同与估值风险：交叉持股不会自动带来收入，仍要观察真实采购、利用率与现金流。",source:"SEC",url:"https://www.sec.gov/edgar/search/",time:"5 分钟"},
{id:"tech-3",section:"科技",kicker:"全球科技 TOP 5 · 开源",title:"Meta 推出可在个人电脑运行的 Muse Glimmer",summary:"开放权重、本地运行和低成本成为前沿能力之外的关键竞争维度。",full:"Meta 发布 Muse Glimmer，并计划向开发者提供更强的 Muse Spark 1.2。可在个人设备运行意味着更低延迟、更多隐私控制和离线场景，也让企业能够在云端前沿模型与本地开放模型之间进行路由。\n\n实际采用仍要核对许可证、硬件占用、评测和安全边界。",source:"Associated Press",url:"https://apnews.com/article/meta-ai-mark-zuckerberg-artificial-intelligence-df8a4e7d7825470d09e8090367457c2c",time:"6 分钟"},
{id:"tech-4",section:"科技",kicker:"全球科技 TOP 5 · 企业软件",title:"Agent 正快速进入法律、销售、招聘与市场岗位",summary:"企业 AI 的下一阶段是把个人技巧沉淀成团队可复用的工作流。",full:"OpenAI 的企业研究显示，自 2 月以来 Codex 在法律、销售、招聘和市场岗位的周活增长明显。领先企业更频繁使用连接上下文、工具和技能的能力。\n\n这意味着企业软件会从“每个页面加聊天框”转向任务编排、权限、复核和审计。",source:"OpenAI",url:"https://openai.com/index/how-enterprises-put-ai-to-work/",time:"7 分钟"},
{id:"tech-5",section:"科技",kicker:"全球科技 TOP 5 · 数字经济",title:"Google ATLAS 显示 AI 已覆盖大量职业，但自动化仍较浅",summary:"真实使用主要集中于构思、检索、学习和协作，完整自动化不到一成交互。",full:"ATLAS v1.0 覆盖 1500 万次去标识化交互、150 多个国家和 800 个职业。数据表明 AI 的扩散很广，但典型岗位只在部分任务中使用。\n\n对科技产业而言，这意味着增长空间来自更深的工作流集成，而不只是新增用户。",source:"Google",url:"https://blog.google/innovation-and-ai/technology/research/understanding-the-ai-economy/",time:"7 分钟"},
{id:"science-2",section:"前沿科学",kicker:"AI for Science · arXiv",title:"OmniScientist 让 AI 直接读取视频、音频、3D 和原始实验数据",summary:"三个 Agent 分别承担构思、实验和写作，并用确定性程序检查统计与数字一致性。",full:"OmniScientist 试图把 AI Scientist 从读论文、写代码扩展到直接理解原始科研证据。论文在五大学科、36 个真实数据案例中测试了从数据到论文的完整流程，并报告直接感知原始数据的版本在多项指标上更好。\n\n这是新预印本，85% 两两比较胜率等结果仍需独立验证，但“多模态科学 Agent”方向值得长期跟踪。",source:"arXiv",url:"https://arxiv.org/abs/2608.13558",time:"9 分钟"},
{id:"science-3",section:"前沿科学",kicker:"量子计算 · Nature",title:"自旋量子比特取得多项关键进展",summary:"四个独立团队在误差率和器件能力上推进了被低估的自旋量子路线。",full:"Nature 近期汇总多项自旋量子比特研究。自旋量子比特有望利用半导体制造基础设施扩大规模，但仍面临控制、读出、噪声和大规模互连问题。\n\n判断量子突破时，应关注逻辑错误率、可扩展制造和系统级演示，而不只看单个器件纪录。",source:"Nature",url:"https://www.nature.com/articles/d41586-026-02400-7",time:"7 分钟"},
{id:"science-4",section:"前沿科学",kicker:"生命科学 · Nature",title:"新型 CRISPR 酶尝试精准破坏携带癌症突变的细胞",summary:"早期实验探索把能切碎 DNA 的蛋白定向到肿瘤突变。",full:"这项研究探索利用特殊 CRISPR 相关酶识别肿瘤突变并破坏细胞 DNA。当前仍属于早期验证，距离临床需要解决脱靶、递送、免疫反应和正常组织安全等问题。\n\n真正重要的是基因编辑工具正从“修改一个位点”扩展到更多可编程治疗机制。",source:"Nature",url:"https://www.nature.com/news",time:"6 分钟"},
{id:"science-5",section:"前沿科学",kicker:"公共卫生 · Nature",title:"古 DNA 提供天花传入美洲的直接基因证据",summary:"智利木乃伊中的病毒序列支持疾病由欧洲人带入的历史判断。",full:"研究人员从历史遗骸中恢复病毒基因信息，为天花进入美洲的时间与传播来源提供直接证据。古病原体基因组能够补充文献记录，并帮助研究疾病、迁徙和社会变化之间的关系。\n\n此类研究同时要求严格处理样本污染、年代测定和伦理问题。",source:"Nature",url:"https://www.nature.com/articles/d41586-026-02452-9",time:"6 分钟"},
{id:"science-6",section:"前沿科学",kicker:"化学与公共安全",title:"机器学习尝试预测超过十亿种潜在芬太尼变体的化学指纹",summary:"研究目标是让检测系统识别尚未被目录收录的新型合成阿片。",full:"研究人员使用机器学习预测大量可能芬太尼变体的质谱等化学特征，以应对新型物质变化快、标准品不足的问题。\n\n该方法的价值在于扩大筛查范围，但实际执法和医疗判断仍需实验室确认、误报评估与标准化流程。",source:"Science News",url:"https://www.sciencenews.org/article/fentanyl-variants-machine-learning",time:"7 分钟"}
);
todayStories.push(
{id:"world-2",section:"新闻",kicker:"世界 TOP 5 · 产业金融",title:"AI 算力建设进入数千亿美元级融资周期",summary:"大型金融机构正在把 GPU 与数据中心长期合同视作可融资基础设施。",full:"NVIDIA 与多家全球资产管理和私募信贷机构探索 AI Compute Financing。它可能加速算力建设，也把模型需求波动、芯片迭代和数据中心利用率风险传导到金融体系。\n\n这是 AI 产业从技术投资扩大为宏观资本开支周期的重要信号。",source:"Reuters",url:"https://www.reuters.com/legal/transactional/private-credit-roundup-nvidias-half-trillion-chips-financing-plus-others-2026-08-14/",time:"6 分钟"},
{id:"world-3",section:"新闻",kicker:"世界 TOP 5 · 就业",title:"AI 对就业的影响开始进入宏观经济政策讨论",summary:"裁员原因与生产率数据正在促使央行和政策机构单独观察 AI 变量。",full:"Reuters 分析指出，AI 已连续数月出现在美国企业披露的裁员原因中，科技、金融与保险等知识工作行业尤其受到关注。现有证据尚不足以把整体失业变化归因于 AI，但政策研究已从假设讨论转向数据跟踪。\n\n真正值得关注的是企业是否从 Copilot 走向直接承担完整流程的 Agent。",source:"Reuters",url:"https://www.reuters.com/commentary/reuters-open-interest/ai-creeps-onto-fed-radar-footprint-is-small-so-far-2026-08-13/",time:"7 分钟"},
{id:"world-4",section:"新闻",kicker:"世界 TOP 5 · 科技政策",title:"美国开放权重模型讨论上升到国家竞争层面",summary:"政策制定者开始讨论如何支持本土开放模型，应对全球开发者生态竞争。",full:"美国议员呼吁政府扶持本土开放权重模型，并把企业可定制、私有化部署与国家技术竞争联系起来。\n\n开放权重并不等于没有限制，后续关键在于许可证、出口管制、安全评测和公共研究资源如何协调。",source:"Reuters",url:"https://www.reuters.com/business/republican-senator-urges-trump-back-us-open-weight-ai-models-amid-industry-2026-08-14/",time:"6 分钟"},
{id:"world-5",section:"新闻",kicker:"世界 TOP 5 · 气候",title:"欧洲极端野火继续考验城市与公共基础设施韧性",summary:"高温、干旱与强风叠加，使法国和西班牙等地面临更复杂的消防压力。",full:"Reuters 持续记录欧洲多地大型野火及其对居民、交通、电力和生态的影响。单次火灾不能简单归因于气候变化，但更高温、更干燥的背景会提高极端火险条件出现的概率。\n\n长期问题是城市规划、预警、保险和跨区域救援能力能否适应更频繁的极端事件。",source:"Reuters",url:"https://www.reuters.com/world/europe/",time:"6 分钟"},
{id:"china-1",section:"新闻",kicker:"中国 TOP 5 · 机器人",title:"人形机器人企业进入上市与规模制造检验阶段",summary:"市场关注点从动作 Demo 转向收入、海外销售、交付与盈利能力。",full:"Unitree 等中国人形机器人企业的上市进程持续受到关注。资本热度背后，更重要的是行业开始接受制造、供应链、海外销售和真实场景部署的检验。\n\n未来胜负不会只由单次展示决定，而取决于数据闭环、可靠性、成本和售后体系。",source:"Reuters",url:"https://www.reuters.com/world/asia-pacific/what-is-unitree-why-are-chinas-humanoid-robot-makers-racing-list-2026-08-10/",time:"7 分钟"},
{id:"china-2",section:"新闻",kicker:"中国 TOP 5 · 大模型",title:"中国开放模型正在影响全球企业的技术选型",summary:"DeepSeek、Qwen、Kimi 等路线增强了低成本、可定制模型的全球竞争。",full:"随着开放模型能力提升，企业的选择从单一海外 API 扩展到开放权重、私有化和多模型路由。对中国企业，数据合规、本地部署、中文与行业语义能力尤其关键。\n\n开放生态的长期竞争还取决于许可证稳定性、开发者工具、推理框架和社区维护。",source:"Reuters",url:"https://www.reuters.com/technology/artificial-intelligence/",time:"6 分钟"},
{id:"china-3",section:"新闻",kicker:"中国 TOP 5 · 具身智能",title:"中国机器人产业把高质量真实数据视为核心资源",summary:"工业机器人采集的交互数据，正在成为训练机器理解物理世界的关键投入。",full:"Reuters 对中国机器人产业的采访显示，企业和研究机构越来越强调从真实工业现场采集高质量数据。与互联网文本不同，机器人数据昂贵、与本体相关，并涉及安全和生产流程。\n\n这使数据采集平台、仿真、遥操作和跨本体迁移成为重要基础设施。",source:"Reuters Connect",url:"https://www.reutersconnect.com/item/chinas-ubtech-highlights-importance-of-data-collection-from-robots/dGFnOnJldXRlcnMuY29tLDIwMjY6bmV3c21sX1ZBMzExNTE2MDQyMDI2UlAx",time:"6 分钟"},
{id:"china-4",section:"新闻",kicker:"中国 TOP 5 · 科研",title:"世界模型开始被用于生成机器人训练场景",summary:"小米 Robotics-U0 展示多视角一致的具身场景和跨机器人迁移。",full:"中国团队发布的 Xiaomi-Robotics-U0 将世界基础模型扩展到机器人训练数据生成，并公开论文、代码与检查点入口。\n\n如果第三方复现确认其分布外操作提升，这类模型可能降低真机数据采集成本，并加快不同机器人本体之间的能力迁移。",source:"arXiv",url:"https://arxiv.org/abs/2607.11643",time:"7 分钟"},
{id:"china-5",section:"新闻",kicker:"中国 TOP 5 · 产业生态",title:"WAIC 之后，机器人与 Physical AI 成为产业关注主线",summary:"展会焦点从聊天模型转向机器人、自动驾驶、产业 Agent 与真实部署。",full:"2026 世界人工智能大会展示了大量机器人和自动化产品。与早期更关注模型参数不同，产业讨论正在转向实际场景、成本、数据、安全和规模交付。\n\n这代表中国 AI 产业的一条重要演进：从 LLM、RAG 和 Agent 继续走向 World Model、VLA 与 Physical AI。",source:"Reuters Connect",url:"https://www.reutersconnect.com/item/world-artificial-intelligence-conference-in-shanghai/dGFnOnJldXRlcnMuY29tLDIwMjY6bmV3c21sX1JDMjZHTUFLSVFXUw",time:"6 分钟"}
);
const aiKnowledge={title:"Embedding：把语义变成可以计算的向量",tag:"大模型核心知识 · 第 2 期",intro:"Embedding，就是把文字、图片、语音等内容转换成一串能够表达含义的数字。它让计算机可以计算两个东西在语义上到底有多像。",points:["语义相似的内容，在向量空间中的位置通常更接近。","Embedding 是语义搜索、向量数据库、RAG、推荐和相似案例匹配的基础。","在反诈场景中，它负责召回相似案件，而不是直接判断某条信息一定是诈骗。"],source:"Word2Vec / Sentence-BERT / SimCSE",url:"https://arxiv.org/abs/1908.10084"};
const briefingMeta={window:"8 月 14 日全球动态",intro:"今天这版继续收紧筛选标准。没有为了凑数选择普通融资或功能小更新，而是保留真正会改变技术路线、产品形态和产业结构的五件事。今天的关键词是：开放权重、AI 算力融资、AI Scientist、World Model、Agent OS。"};
const briefingNotes:Record<string,{why:string;insight:string;rating:string}>={
 "ai-1":{rating:"★★★★★",why:"生成内容的来源标记开始从行业倡议进入模型默认能力。水印不能独立证明真假，但会成为内容平台、企业审计和监管合规的新基础设施。",insight:"产品设计要把“AI 是否参与”“内容是否真实”“由谁发布”拆成三个问题，并结合水印、C2PA、来源引用和人工核验。"},
 "ai-2":{rating:"★★★★★",why:"企业 AI 的价值衡量正在从回答质量转向能否承担完整 Workflow。领先企业真正拉开差距的，是上下文、工具、权限和可复用工作流。",insight:"以后评估 Agent，不只问模型聪不聪明，而要问：能否稳定完成任务、失败后恢复、留下审计记录，并交付可复核的结果。"},
 "ai-3":{rating:"★★★★★",why:"开放权重与封闭前沿模型正在形成两条长期路线。本地运行、成本和私有化能力，会直接影响金融、运营商、安全和反诈等行业的选型。",insight:"高难任务用 Frontier API，大规模重复任务用开放模型，敏感数据私有化，端侧执行用小模型；多模型路由会成为常态。"},
 "ai-4":{rating:"★★★★☆",why:"Agent 连续调用模型几十甚至上百次后，单次价格差异会被成倍放大，因此“够强且便宜”可能比单项榜单第一更有商业价值。",insight:"模型评价应拆成：智能水平 × Token 成本 × 延迟 × Tool Calling × 长任务稳定性，而不是只比较 Benchmark。"},
 "ai-5":{rating:"★★★★★",why:"1500 万次真实交互显示，AI 当前主要渗透具体任务，而不是一次替代整个职业；完全自动化仍然少见。",insight:"产品应围绕岗位中的具体步骤设计，先找到高摩擦、高频、可复核的任务，再逐步从 Copilot 走向 Agent。"}
};
const knowledgeSections=[
 {title:"1. 为什么文字必须变成向量？",body:"计算机天然不知道“刷单返利诈骗”和“做任务先垫钱，完成后返佣金”是不是一回事。关键词重复很少，但语义高度相关。Embedding 把它们变成向量，让语义相似的内容在向量空间中彼此靠近。"},
 {title:"2. 把 Embedding 想象成语义地图",body:"现实地图用经纬度描述城市位置；Embedding 用几百或上千个数字描述内容在语义空间的位置。单独一维通常没有简单含义，整个向量共同表达语义。"},
 {title:"3. Embedding 是怎么学出来的？",body:"Word2Vec 的核心思想是：经常出现在相似上下文里的词，语义往往相近。模型不是被程序员告知苹果、华为、小米都是手机品牌，而是从海量文本关系中学习它们的位置。"},
 {title:"4. 从词向量到句子与文档向量",body:"Transformer 之后，Embedding 从单词扩展到句子、段落和文档。Sentence-BERT 让句向量可以高效比较，为语义检索、知识库和 RAG 的规模化落地奠定基础。"},
 {title:"5. 两个向量怎么判断像不像？",body:"最常见的方法之一是余弦相似度：比较两个向量方向是否接近。0.96 可以表示非常相似，但阈值不是固定业务标准，必须结合具体模型和真实数据评估。"},
 {title:"6. 放到反诈场景里",body:"“兼职做任务，首次充值 300 元，完成后返还 390 元”可以召回历史的“刷单返利诈骗”案例。Embedding 做的不是直接判定诈骗，而是找到语义最相近的已知诈骗模式。"},
 {title:"7. 完整的反诈产品流程",body:"新风险事件 → 文本清洗 → Embedding Model → Vector Database → Top-K 相似案例 → Reranker → LLM 综合研判 → 输出诈骗类型、风险等级、历史案例、理由和处置建议。"},
 {title:"8. Embedding 与关键词搜索",body:"关键词检索关注字面是否匹配，Embedding 关注语义是否接近。成熟系统通常采用 Hybrid Search：手机号、银行卡和域名用精确匹配，话术、投诉描述和案件摘要用向量检索。"},
 {title:"9. Embedding 与向量数据库",body:"Embedding Model 是翻译器，负责把内容变成向量；Vector Database 是仓库和搜索引擎，负责存储并查找相似向量。两者不是同一个东西。"},
 {title:"10. Embedding 与 RAG",body:"用户提问先生成 Embedding，再从知识库召回相关资料，最后交给 LLM 阅读和回答。可以简单记成：Embedding 帮你找资料，LLM 帮你理解并生成答案。"},
 {title:"11. Embedding Model 不等于 LLM",body:"Embedding 模型主要完成“文本 → 向量”，LLM 主要完成“文本 → 文本”。实际产品往往把 Embedding、Reranker 和 LLM 组合起来工作。"},
 {title:"12. 对比学习与困难负样本",body:"对比学习把相似内容拉近、不相似内容推远。“刷单返利诈骗”和“正常电商返现活动”文字很像但性质不同，是反诈模型中特别有价值的 Hard Negative。"},
 {title:"13. 产品经理真正应该关注什么？",body:"不要只看 768 维或公开榜单。更重要的是 Recall@K、误召回、困难负样本表现，以及模型能否理解杀猪盘、跑分、GOIP、引流和涉诈网址等行业语义。"},
 {title:"14. 最常见的五个坑",body:"只看模型榜单；所有内容都用向量检索；Chunk 切分不合理；把相似度误当诈骗概率；召回后不经过 Reranker、规则、分类模型或 LLM 继续判断。"},
 {title:"15. 三篇值得看的经典论文",body:"Word2Vec（2013）解释词义如何从关系中学习；Sentence-BERT（2019）让句子语义搜索高效落地；SimCSE（2021）展示如何用对比学习改善句向量空间。"}
];

export default function Home(){
 const[active,setActive]=useState("今日"),[selectedDate,setSelectedDate]=useState("today"),[dateOpen,setDateOpen]=useState(false),[query,setQuery]=useState(""),[searchOpen,setSearchOpen]=useState(false),[expanded,setExpanded]=useState<string|null>(null),[knowledgeOpen,setKnowledgeOpen]=useState(false),[votes,setVotes]=useState<Record<string,1|-1>>({}),[favorites,setFavorites]=useState<Story[]>([]),[isAdmin,setIsAdmin]=useState(false),[accountOpen,setAccountOpen]=useState(false),[loggedIn,setLoggedIn]=useState<boolean|null>(null),[error,setError]=useState(""),[loading,setLoading]=useState(false),[selectedText,setSelectedText]=useState(""),[selectionMenu,setSelectionMenu]=useState<{x:number;y:number}|null>(null),[reading,setReading]=useState<"idle"|"speaking"|"paused"|"done">("idle");
 const speechRef=useRef<SpeechSynthesisUtterance|null>(null);
 const today=useMemo(()=>new Intl.DateTimeFormat("zh-CN",{month:"long",day:"numeric",weekday:"long",timeZone:"Asia/Shanghai"}).format(new Date()),[]);
 useEffect(()=>{fetch("/api/session").then(async r=>{setLoggedIn(r.ok);if(r.ok){const s=await r.json();setIsAdmin(s.isAdmin);const f=await fetch("/api/favorites");if(f.ok)setFavorites((await f.json()).favorites)}}).catch(()=>setLoggedIn(false));navigator.serviceWorker?.register("/sw.js")},[]);
 useEffect(()=>{
  const handleSelection=()=>{
   const selection=window.getSelection();
   const text=selection?.toString().replace(/\s+/g," ").trim()||"";
   if(!selection||!text||selection.rangeCount===0){setSelectionMenu(null);return}
   const node=selection.anchorNode instanceof Element?selection.anchorNode:selection.anchorNode?.parentElement;
   if(!node?.closest("article, .knowledge")){setSelectionMenu(null);return}
   const rect=selection.getRangeAt(0).getBoundingClientRect();
   setSelectedText(text);setSelectionMenu({x:Math.min(Math.max(rect.left,12),window.innerWidth-118),y:Math.min(rect.bottom+10,window.innerHeight-76)});
  };
  const stopOnLeave=()=>{window.speechSynthesis?.cancel();setReading("idle");speechRef.current=null};
  const handleVisibility=()=>{if(document.hidden)stopOnLeave()};
  document.addEventListener("selectionchange",handleSelection);
  document.addEventListener("visibilitychange",handleVisibility);
  window.addEventListener("pagehide",stopOnLeave);
  return()=>{document.removeEventListener("selectionchange",handleSelection);document.removeEventListener("visibilitychange",handleVisibility);window.removeEventListener("pagehide",stopOnLeave);stopOnLeave()};
 },[]);
 function closeSelection(){window.getSelection()?.removeAllRanges();setSelectionMenu(null);setSelectedText("")}
 function chooseChineseVoice(){const voices=window.speechSynthesis?.getVoices()||[];return voices.find(v=>/^zh(-|_)/i.test(v.lang)&&/女|female|ting|xiaoxiao|sin-ji|yaoyao/i.test(v.name))||voices.find(v=>/^zh(-|_)/i.test(v.lang))}
 function startReading(text=selectedText){if(!text||!window.speechSynthesis)return;window.speechSynthesis.cancel();const utterance=new SpeechSynthesisUtterance(text);utterance.lang="zh-CN";utterance.rate=.92;utterance.pitch=1.08;utterance.volume=1;const voice=chooseChineseVoice();if(voice)utterance.voice=voice;utterance.onstart=()=>setReading("speaking");utterance.onpause=()=>setReading("paused");utterance.onresume=()=>setReading("speaking");utterance.onend=()=>{setReading("done");speechRef.current=null};utterance.onerror=()=>{setReading("idle");speechRef.current=null};speechRef.current=utterance;setSelectionMenu(null);window.speechSynthesis.speak(utterance)}
 function toggleReading(){if(!speechRef.current)return;if(reading==="speaking")window.speechSynthesis.pause();else if(reading==="paused")window.speechSynthesis.resume();else startReading()}
 function stopReading(){window.speechSynthesis?.cancel();speechRef.current=null;setReading("idle");closeSelection()}
 async function login(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setLoading(true);setError("");const body=Object.fromEntries(new FormData(e.currentTarget));const r=await fetch("/api/login",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(body)});if(r.ok)setLoggedIn(true);else setError("账号或密码不正确");setLoading(false)}
 async function vote(id:string,value:1|-1){setVotes(v=>({...v,[id]:value}));await fetch("/api/feedback",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({storyId:id,value})})}
 async function favorite(story:Story){const active=!favorites.some(s=>s.id===story.id);setFavorites(f=>active?[story,...f]:f.filter(s=>s.id!==story.id));await fetch("/api/favorites",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({story,active})})}
 async function share(story:Story){const data={title:story.title,text:story.summary,url:`${location.origin}/#story-${story.id}`};if(navigator.share)await navigator.share(data);else{await navigator.clipboard.writeText(`${data.title}\n${data.text}\n${data.url}`);alert("分享内容已复制")}}
 async function addAccount(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const body=Object.fromEntries(new FormData(e.currentTarget));const r=await fetch("/api/accounts",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(body)});const data=await r.json();alert(r.ok?"账号已创建":data.error);if(r.ok){e.currentTarget.reset();setAccountOpen(false)}}
 async function installApp(){alert("在 iPhone Safari 中点击底部分享按钮，然后选择“添加到主屏幕”。")}
 if(loggedIn===null)return <main className="loading">STELLAR<span>.</span></main>;
 if(!loggedIn)return <main className="login-shell"><section className="login-card"><img className="app-icon" src="/apple-touch-icon.png" alt="Stellar"/><p className="eyebrow">STELLAR DAILY</p><h1>每天，少一点噪声。<br/>多一点理解。</h1><p className="login-copy">AI · 具身智能 · 科技 · 新闻<br/>为你精选的每日情报。</p><form onSubmit={login}><label>账号<input name="username" autoComplete="username" required/></label><label>密码<input name="password" type="password" autoComplete="current-password" required/></label>{error&&<p className="error">{error}</p>}<button disabled={loading}>{loading?"正在登录…":"继续"}</button></form><p className="privacy">登录状态将在此设备保留 90 天</p></section></main>;
 const all=selectedDate==="today"?todayStories:archives[selectedDate];const shown=active==="收藏"?favorites:active==="今日"?all:all.filter(s=>s.section===active);const selected=dates.find(d=>d.key===selectedDate)!;const index=[{date:"today",stories:todayStories},...Object.entries(archives).map(([date,stories])=>({date,stories}))];const results=query.trim()?index.flatMap(g=>g.stories.filter(s=>`${s.section} ${s.kicker} ${s.title} ${s.summary} ${s.full||""}`.toLowerCase().includes(query.trim().toLowerCase())).map(story=>({date:g.date,story}))):[];
 function jump(date:string,story:Story){setSelectedDate(date);setActive(story.section);setExpanded(story.id);setSearchOpen(false);setQuery("");setTimeout(()=>document.querySelector("article.open")?.scrollIntoView({behavior:"smooth",block:"center"}),150)}
 return <main><header><a className="brand" href="#top">Stellar</a><nav>{nav.map(n=><button className={active===n?"active":""} onClick={()=>setActive(n)} key={n}>{createElement(navIcons[n],{size:18,strokeWidth:1.8})}<span>{n}</span></button>)}</nav><button className="install" onClick={installApp}><Download size={16}/>安装 App</button>{isAdmin&&<button className="account-btn" onClick={()=>setAccountOpen(true)}><UserRoundPlus size={16}/>账号</button>}<button className="avatar" onClick={async()=>{await fetch("/api/logout",{method:"POST"});setLoggedIn(false)}}>LY</button></header>{accountOpen&&<div className="modal-backdrop" onClick={()=>setAccountOpen(false)}><section className="account-modal" onClick={e=>e.stopPropagation()}><button className="modal-close" onClick={()=>setAccountOpen(false)}><X/></button><UserRoundPlus className="modal-icon"/><h2>新增登录账号</h2><p>新账号可以独立登录、收藏和使用兴趣反馈。</p><form onSubmit={addAccount}><label>账号<input name="username" minLength={3} maxLength={24} required/></label><label>密码<input name="password" type="password" minLength={8} required/></label><button>创建账号</button></form></section></div>}
 <section className="hero" id="top"><div className="hero-top"><img src="/icon-192.png" alt=""/><p className="date">{selectedDate==="today"?`${today} · 北京`:`${selected.sub} · 历史归档`}</p></div><h1>{active==="今日"?<>今天，有什么<br/><em>值得知道？</em></>:<>{active}<br/><em>每日精选</em></>}</h1><p className="intro">完整中文内容已缓存在站内。来源链接仅用于核验，阅读无需离开 Stellar。</p><div className="pulse"><i/> 内容已归档 <span>02:16</span></div></section>
 <section className="search-wrap"><div className="search-box"><Search size={19}/><input value={query} onFocus={()=>setSearchOpen(true)} onChange={e=>{setQuery(e.target.value);setSearchOpen(true)}} placeholder="搜索全年内容，例如 ROS"/><select aria-label="年份"><option>2026</option></select>{query&&<button onClick={()=>setQuery("")}><X size={17}/></button>}</div>{searchOpen&&query&&<div className="search-results"><div className="search-count">2026 年 · 找到 {results.length} 条结果</div>{results.map(({date,story})=><button key={story.id} onClick={()=>jump(date,story)}><span><small>{date==="today"?"今天":date} · {story.section}</small><b>{story.title}</b><em>{story.summary}</em></span><ChevronRight size={19}/></button>)}{!results.length&&<p>没有找到相关归档</p>}</div>}</section>
 <section className="date-wrap"><button className="date-current" onClick={()=>setDateOpen(!dateOpen)}><span className="date-icon"><CalendarDays size={20}/></span><span><b>{selected.label}</b><small>{selected.sub} · {all.length} 篇精选</small></span>{dateOpen?<ChevronUp size={18}/>:<ChevronDown size={18}/>}</button>{dateOpen&&<div className="date-list">{dates.map(d=><button className={selectedDate===d.key?"selected":""} key={d.key} onClick={()=>{setSelectedDate(d.key);setDateOpen(false);setExpanded(null)}}><span>{d.label}</span><small>{d.sub}</small></button>)}</div>}</section>
 {selectedDate==="today"&&(active==="今日"||active==="AI")&&<section className={`knowledge ${knowledgeOpen?"expanded":""}`}><div className="knowledge-label"><span>大模型核心知识</span><small>{aiKnowledge.tag}</small></div><div className="knowledge-main"><div><h2>{aiKnowledge.title}</h2><p>{aiKnowledge.intro}</p></div><ol>{aiKnowledge.points.map((p,i)=><li key={p}><b>0{i+1}</b><span>{p}</span></li>)}</ol></div>{knowledgeOpen&&<div className="knowledge-course"><blockquote>Embedding 负责“找到相关内容”，LLM 更擅长“理解并生成答案”。</blockquote>{knowledgeSections.map(s=><section key={s.title}><h3>{s.title}</h3><p>{s.body}</p></section>)}<div className="paper-links"><a href="https://arxiv.org/abs/1301.3781" target="_blank" rel="noreferrer">Word2Vec ↗</a><a href="https://arxiv.org/abs/1908.10084" target="_blank" rel="noreferrer">Sentence-BERT ↗</a><a href="https://arxiv.org/abs/2104.08821" target="_blank" rel="noreferrer">SimCSE ↗</a></div><pre>{`Transformer\n  └─ Embedding → Vector Search → RAG → Reranker → LLM → Agent`}</pre><p className="next-course">下一期：向量检索——几百万条案例变成向量以后，系统如何在毫秒级找到最相似的几条？</p></div>}<div className="knowledge-foot"><button onClick={()=>setKnowledgeOpen(!knowledgeOpen)}>{knowledgeOpen?"收起课程":"阅读全文 · 15 个章节"}</button><a href={aiKnowledge.url} target="_blank" rel="noreferrer">论文来源 · {aiKnowledge.source} ↗</a></div></section>}
 <section className="feed">{active==="AI"&&selectedDate==="today"&&<div className="briefing-deck"><span>🌍 全球 AI 每日 5 件事 · 8 月 15 日</span><small>统计窗口：{briefingMeta.window}</small><p>{briefingMeta.intro}</p></div>}<div className="section-head"><div><p className="eyebrow">{active==="收藏"?"MY LIBRARY":active==="AI"&&selectedDate==="today"?"GLOBAL AI DAILY 5":`${selected.sub} · ARCHIVE`}</p><h2>{active==="今日"?"值得关注":active==="AI"&&selectedDate==="today"?"全球 AI 每日 5 件事":active}</h2></div><p>{shown.length} 篇站内全文</p></div>{active==="收藏"&&!shown.length&&<div className="empty-state"><Bookmark/><h3>还没有收藏</h3><p>点击文章右侧的书签即可保存。</p></div>}{shown.map((s,i)=>{const open=expanded===s.id,starred=favorites.some(f=>f.id===s.id),note=briefingNotes[s.id];return <article id={`story-${s.id}`} className={open?"open":""} key={s.id}><div className="story-number">{String(i+1).padStart(2,"0")}</div><div className="story-body"><p className="kicker">{s.section} · {s.kicker}</p><button className="story-toggle" onClick={()=>setExpanded(open?null:s.id)}><h3>{s.title}</h3>{open?<ChevronUp/>:<ChevronDown/>}</button><p className="summary">{s.summary}</p>{open&&<div className="full-text">{(s.full||`${s.summary}\n\n这篇内容已整理为站内中文版本，保留关键背景、影响与后续观察方向。`).split("\n").map((p,j)=>p&&<p key={j}>{p}</p>)}{note&&<><div className="editor-note"><h4>为什么重要？ <b>{note.rating}</b></h4><p>{note.why}</p></div><div className="editor-note insight"><h4>产品启发</h4><p>{note.insight}</p></div></>}<div className="source-note"><span>原始来源</span><a href={s.url} target="_blank" rel="noreferrer">{s.source} ↗</a></div></div>}<div className="meta"><span>{s.time} 阅读</span><button onClick={()=>setExpanded(open?null:s.id)}>{open?"收起全文":"站内阅读全文"}</button></div></div><div className="actions"><button aria-label="收藏" className={starred?"selected favorite":""} onClick={()=>favorite(s)}><Bookmark size={16} fill={starred?"currentColor":"none"}/></button><button aria-label="分享" onClick={()=>share(s)}><Share2 size={16}/></button><button aria-label="喜欢" className={votes[s.id]===1?"selected":""} onClick={()=>vote(s.id,1)}><ThumbsUp size={16}/></button><button aria-label="不喜欢" className={votes[s.id]===-1?"selected down":""} onClick={()=>vote(s.id,-1)}><ThumbsDown size={16}/></button></div></article>})}{active==="AI"&&selectedDate==="today"&&<div className="briefing-summary"><p className="eyebrow">TODAY'S SIGNAL</p><h3>今天最值得记住的三条线</h3><p><b>开放权重</b>正在上升为企业与国家级技术路线；<b>Agent</b>从回答走向完整工作流；<b>AI 基础设施</b>开始同时由算法、芯片、部署和金融成本驱动。</p></div>}</section>
 {selectionMenu&&<button className="reading-selection" style={{left:selectionMenu.x,top:selectionMenu.y}} onMouseDown={e=>e.preventDefault()} onClick={()=>startReading()}><Volume2 size={16}/>朗读</button>}{reading!=="idle"&&<div className="reading-bar" role="status"><div className="reading-status"><Volume2 size={18}/><span>{reading==="done"?"朗读完成":reading==="paused"?"已暂停":"正在朗读"}</span><small>{selectedText.slice(0,28)}{selectedText.length>28?"…":""}</small></div>{reading!=="done"&&<button aria-label={reading==="paused"?"继续朗读":"暂停朗读"} onClick={toggleReading}>{reading==="paused"?<Play size={18}/>:<Pause size={18}/>}</button>}<button aria-label="停止朗读" onClick={stopReading}><Square size={16}/></button></div>}<footer><a className="brand" href="#top">Stellar</a><p>每天 15 分钟，看懂 AI 与世界。</p><p>历史内容持续归档</p></footer></main>
}
